### ISSUE TITLE
Add embossed effect to heading text and colored elements

### ISSUE THREAD

**Issue by jerboa88** [jerboa88/jerboa88.github.io#97]
Add embossed effect to elements to create more depth when dark mode is used.

**Tasks**:
- [ ] Reduce brightness of `base-content` color
- [x] Change `neutral` color to pure white
- [ ] Add embossed effect to heading text and colored elements

**Comment by jerboa88** [comment]
Neutral color changed in 331f271

**Comment by jerboa88** [comment]
Completed in #125
