### ISSUE TITLE
Add tilt effect to cards on hover

### ISSUE THREAD

**Issue by jerboa88** [jerboa88/jerboa88.github.io#98]
Add tilt effect to interactive elements like cards and buttons to increase depth and interactivity of the site.

**Tasks**:
- [x] Implement 3d transform on hover for Card component
- [x] Implement lighting effect on hover for Card component
- [x] Reimplement CSS scale effect on hover with Framer Motion
- [x] Modify button components to use Card component?
- [x] Make sure card border colors and widths are consistent with those of other elements (inputs, buttons, headers, footers, dividers, etc.)
- [x] Disable hover effects on mobile
- [x] Disable hover effects when components are disabled
- [x] Add gradient background to other page elements (header, footer, buttons, body, etc.)
- [x] Modify card gradient template string to take the elements position on the page into account? This will allow for more realistic lighting effects
- [x] Increase the gradient size of an element on hover to simulate an elevation change?

**Comment by jerboa88** [comment]
Completed in #100
